version: '3.7'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: book_lib
      MYSQL_USER: myuser
    ports:
      - "3307:3306"  # Порт 3306 контейнера на 3307 хоста
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-network

  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=book_lib
    ports:
      - "8085:8085"
    depends_on:
      - db
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  mysql_data:
